### ISSUE TITLE
feat: 어디가개 - 예약, 결제정보 서버로 전송

### ISSUE THREAD

**Issue by greenish0902** [greenish0902/puppy-walk#32]
# Todos
__예약 기능 & 결제 기능__
- [ ] 1. 예약 정보 입력받아 전역 상태로 관리
- [ ] 2. 예약 장소에 맞는 결제 (IamPort)
- [ ] 3. 결제 완료시 예약정보 서버로 전송
- [ ] 4. 마이페이지로 redirect해서 예약된 정보 확인

## 예정된 Task
- 예약 완료된 마이페이지 View 구현
- 예약 정보 CRUD
